interface ReportMetrics {
  afterSales: any;
  kpi: any;
  competitors: any;
  sales: any;
  debt: any;
  tasks: any;
}

export function generateReportContent(
  metrics: ReportMetrics,
  reportType: string,
  config: { title: string; period: string },
  currencySymbol: string
): string {
  const date = new Date().toLocaleDateString();
  
  let reportContent = `📌 ${config.title} — AI INSIGHT GENERATED\n\n`;
  reportContent += `⚠️ Report Notice:\n`;
  reportContent += `This report is automatically generated using the AI Insight Analytical System, based on real-time operational, financial, and customer data collected across all modules.\n\n`;
  reportContent += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n`;
  
  reportContent += `1. REPORT OVERVIEW\n\n`;
  reportContent += `Date: ${date}\n`;
  reportContent += `Generated By: AI Insight System - Pocket CRM\n`;
  reportContent += `Period: ${config.period}\n`;
  reportContent += `Purpose: Provide ${reportType} performance updates, issues, and recommended actions.\n\n`;
  reportContent += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n`;
  
  reportContent += `2. EXECUTIVE SUMMARY\n\n`;
  reportContent += `Total Active Items: ${metrics.afterSales.total + metrics.kpi.total + metrics.sales.total + metrics.debt.total + metrics.tasks.total}\n`;
  reportContent += `Overall System Health: ${metrics.kpi.avgProgress.toFixed(1)}%\n`;
  reportContent += `Customer Satisfaction: ${(metrics.afterSales.avgSatisfaction * 20).toFixed(0)}%\n`;
  reportContent += `Task Completion Rate: ${metrics.tasks.completionRate.toFixed(1)}%\n`;
  reportContent += `Collection Rate: ${metrics.debt.collectionRate.toFixed(1)}%\n\n`;
  reportContent += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n`;
  
  reportContent += `3. MODULE PERFORMANCE ANALYSIS\n\n`;
  
  reportContent += `3.1 AFTER-SALES FOLLOW-UP\n\n`;
  reportContent += `• Total Orders: ${metrics.afterSales.total}\n`;
  reportContent += `• Completed: ${metrics.afterSales.completed} (${((metrics.afterSales.completed/metrics.afterSales.total)*100).toFixed(1)}%)\n`;
  reportContent += `• In Progress: ${metrics.afterSales.inProgress}\n`;
  reportContent += `• Pending: ${metrics.afterSales.pending}\n`;
  reportContent += `• Average Satisfaction: ${metrics.afterSales.avgSatisfaction.toFixed(1)}/5.0\n`;
  reportContent += `• Total Revenue Tracked: ${currencySymbol}${metrics.afterSales.totalRevenue.toLocaleString()}\n`;
  reportContent += `• Performance Change: ${metrics.afterSales.change > 0 ? '+' : ''}${metrics.afterSales.change}%\n\n`;
  
  reportContent += `3.2 KPI TRACKING\n\n`;
  reportContent += `• Total KPIs: ${metrics.kpi.total}\n`;
  reportContent += `• Achieved: ${metrics.kpi.achieved} ✅\n`;
  reportContent += `• On Track: ${metrics.kpi.onTrack} 🟡\n`;
  reportContent += `• At Risk: ${metrics.kpi.atRisk} ⚠️\n`;
  reportContent += `• Average Progress: ${metrics.kpi.avgProgress.toFixed(1)}%\n`;
  reportContent += `• Performance Change: ${metrics.kpi.change > 0 ? '+' : ''}${metrics.kpi.change}%\n\n`;
  
  reportContent += `3.3 COMPETITOR INTELLIGENCE\n\n`;
  reportContent += `• Total Competitors Tracked: ${metrics.competitors.total}\n`;
  reportContent += `• Active Monitoring: ${metrics.competitors.tracked}\n`;
  reportContent += `• High Threats: ${metrics.competitors.threats}\n`;
  reportContent += `• Market Opportunities: ${metrics.competitors.opportunities}\n`;
  reportContent += `• Average Competitor Price: ${currencySymbol}${metrics.competitors.avgPrice.toLocaleString()}\n`;
  reportContent += `• Data Change: ${metrics.competitors.change > 0 ? '+' : ''}${metrics.competitors.change}%\n\n`;
  
  reportContent += `3.4 SALES & MARKETING STRATEGIES\n\n`;
  reportContent += `• Total Strategies: ${metrics.sales.total}\n`;
  reportContent += `• Active: ${metrics.sales.active}\n`;
  reportContent += `• Completed: ${metrics.sales.completed}\n`;
  reportContent += `• Pending: ${metrics.sales.pending}\n`;
  reportContent += `• Average Effectiveness: ${metrics.sales.avgEffectiveness.toFixed(1)}%\n`;
  reportContent += `• Performance Change: ${metrics.sales.change > 0 ? '+' : ''}${metrics.sales.change}%\n\n`;
  
  reportContent += `3.5 DEBT COLLECTION\n\n`;
  reportContent += `• Total Outstanding: ${metrics.debt.total} accounts\n`;
  reportContent += `• Total Amount: ${currencySymbol}${metrics.debt.totalAmount.toLocaleString()}\n`;
  reportContent += `• Overdue Accounts: ${metrics.debt.overdue}\n`;
  reportContent += `• Overdue Amount: ${currencySymbol}${metrics.debt.overdueAmount.toLocaleString()}\n`;
  reportContent += `• Collected: ${metrics.debt.collected} accounts\n`;
  reportContent += `• Collected Amount: ${currencySymbol}${metrics.debt.collectedAmount.toLocaleString()}\n`;
  reportContent += `• Collection Rate: ${metrics.debt.collectionRate.toFixed(1)}%\n`;
  reportContent += `• Performance Change: ${metrics.debt.change > 0 ? '+' : ''}${metrics.debt.change}%\n\n`;
  
  reportContent += `3.6 TASK MANAGEMENT\n\n`;
  reportContent += `• Total Tasks: ${metrics.tasks.total}\n`;
  reportContent += `• Completed: ${metrics.tasks.completed} (${((metrics.tasks.completed/metrics.tasks.total)*100 || 0).toFixed(1)}%)\n`;
  reportContent += `• In Progress: ${metrics.tasks.inProgress}\n`;
  reportContent += `• Pending: ${metrics.tasks.pending}\n`;
  reportContent += `• Overdue: ${metrics.tasks.overdue} ⚠️\n`;
  reportContent += `• Completion Rate: ${metrics.tasks.completionRate.toFixed(1)}%\n`;
  reportContent += `• Performance Change: ${metrics.tasks.change > 0 ? '+' : ''}${metrics.tasks.change}%\n\n`;
  
  reportContent += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n`;
  
  reportContent += `4. AI-DETECTED ISSUES & RISKS\n\n`;
  if (metrics.debt.overdue > 0) {
    reportContent += `⚠️ HIGH PRIORITY:\n`;
    reportContent += `• ${metrics.debt.overdue} overdue debt accounts detected\n`;
    reportContent += `• Total overdue amount: ${currencySymbol}${metrics.debt.overdueAmount.toLocaleString()}\n\n`;
  }
  if (metrics.kpi.atRisk > 0) {
    reportContent += `⚠️ MEDIUM PRIORITY:\n`;
    reportContent += `• ${metrics.kpi.atRisk} KPIs at risk of not meeting targets\n`;
    reportContent += `• Immediate action required to get back on track\n\n`;
  }
  if (metrics.competitors.threats > 0) {
    reportContent += `⚠️ COMPETITIVE THREAT:\n`;
    reportContent += `• ${metrics.competitors.threats} high-threat competitors identified\n`;
    reportContent += `• Market positioning requires strategic review\n\n`;
  }
  if (metrics.afterSales.pending > 0) {
    reportContent += `⚠️ OPERATIONAL:\n`;
    reportContent += `• ${metrics.afterSales.pending} pending after-sales follow-ups\n`;
    reportContent += `• Customer satisfaction may be impacted\n\n`;
  }
  if (metrics.tasks.overdue > 0) {
    reportContent += `⚠️ TASK MANAGEMENT:\n`;
    reportContent += `• ${metrics.tasks.overdue} overdue tasks requiring immediate attention\n`;
    reportContent += `• Task completion rate: ${metrics.tasks.completionRate.toFixed(1)}%\n\n`;
  }
  
  reportContent += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n`;
  
  reportContent += `5. AI RECOMMENDATIONS\n\n`;
  reportContent += `IMMEDIATE ACTIONS:\n`;
  if (metrics.debt.overdue > 0) {
    reportContent += `• Prioritize debt collection efforts on ${metrics.debt.overdue} overdue accounts\n`;
    reportContent += `• Deploy AI agents for automated follow-up via WhatsApp/SMS\n`;
  }
  if (metrics.kpi.atRisk > 0) {
    reportContent += `• Review ${metrics.kpi.atRisk} at-risk KPIs and adjust strategies\n`;
  }
  if (metrics.afterSales.pending > 0) {
    reportContent += `• Process ${metrics.afterSales.pending} pending after-sales follow-ups\n`;
  }
  if (metrics.tasks.overdue > 0) {
    reportContent += `• Address ${metrics.tasks.overdue} overdue tasks immediately - reassign or reprioritize\n`;
  }
  reportContent += `\nSTRATEGIC ACTIONS:\n`;
  reportContent += `• Continue monitoring competitor movements (${metrics.competitors.tracked} active)\n`;
  reportContent += `• Optimize sales strategies based on effectiveness data\n`;
  reportContent += `• Maintain customer satisfaction above ${(metrics.afterSales.avgSatisfaction * 20).toFixed(0)}%\n`;
  reportContent += `• Improve task completion rate from ${metrics.tasks.completionRate.toFixed(1)}%\n`;
  reportContent += `• Improve collection rate from ${metrics.debt.collectionRate.toFixed(1)}%\n\n`;
  
  reportContent += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n`;
  
  reportContent += `6. NEXT PERIOD FOCUS\n\n`;
  reportContent += `• Address all high-priority issues identified above\n`;
  reportContent += `• Monitor KPI progress daily to prevent at-risk items\n`;
  reportContent += `• Continue competitive intelligence gathering\n`;
  reportContent += `• Strengthen customer relationship management\n`;
  reportContent += `• Improve task management completion rate and reduce overdue tasks\n`;
  reportContent += `• Optimize debt collection processes\n\n`;
  
  reportContent += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n`;
  reportContent += `Generated by Pocket CRM AI Insight System\n`;
  reportContent += `Report Type: ${config.title}\n`;
  reportContent += `Date: ${date}\n`;
  
  return reportContent;
}
