name: copcca-crm
services:
  - name: web
    github:
      repo: narotametro/Copccacrm
      branch: main
      deploy_on_push: true
    build_command: npm run build
    run_command: npx serve -s dist -l 8080
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
    source_dir: /
    output_dir: dist
