name: copcca-crm
static_sites:
  - name: web
    github:
      repo: narotametro/Copccacrm
      branch: main
      deploy_on_push: true
    build_command: npm run build
    output_dir: dist
    catchall_document: index.html
    error_document: index.html
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
